# Parse the conunter file generated by streamline
from os import system
import subprocess

def parse(file_name, rank, iter_step):
    print("---check {} Advec iterstep {}---".format(file_name,iter_step))
    labelstr = "rank_"+str(rank)+"_Advec_iterstep_" + str(iter_step)
    command = "cat " + file_name + " |grep Advec " + "|grep " + "_" + str(iter_step) + "_" + "| cut -d \" \" -f 2 | python3 analysis.py "
    
    command = command+labelstr

    print(command)
    
    system(command)
    
    print("---check {} Recv iterstep {}---".format(file_name,iter_step))
    labelstr = "rank_"+str(rank)+"_Recv_iterstep_" + str(iter_step)
    command = "cat " + file_name + " |grep Received "+ "|grep " + "_" + str(iter_step) + "_" + "| cut -d \" \" -f 2 | python3 analysis.py "

    command = command+labelstr

    system(command)

if __name__ == "__main__":
    procs = 4
    step_start = 10
    step_end = 20
    visit_freq=10
    for s in range (step_start,step_end,visit_freq):
        for i in range (0,procs,1):
            file_name = "counter."+str(i)+".out"
            parse(file_name,i,s)
